Add files to source reference options
Edirom/MerMEId pull request #46
Opened 2020-12-18 16:34 UTC by MauPalantir

![relations](https://user-images.githubusercontent.com/445895/102638122-504b3b80-4157-11eb-95e8-b2fec7b9736a.png)

2021-02-15 17:08 UTC, dasch124 commented
If I read it correctly, this PR should add a "Relations" selector to the "Components" list, right? 
It seems, however, that the input fields (which should be populated with the work list) are disabled ? at least this is what the css classes seem to suggest.

![grafik](https://user-images.githubusercontent.com/4641281/107975221-16ac7a80-6fb8-11eb-971a-97688535d70e.png)
![grafik](https://user-images.githubusercontent.com/4641281/107975589-9c302a80-6fb8-11eb-84f8-c93f6cd436e3.png)

(FWIW: I tried this by checking out the PR's branch and building a fresh docker image from it, hope that's the way to do things)

2021-02-16 08:57 UTC, dasch124 requested changes
as written in the https://github.com/Edirom/MerMEId/pull/46#issuecomment-779352995: the input fields are disabled – maybe the nodeset m:relationList is simply not present in the components of the test data, so orbeon just hides the input fields?

2021-10-04 12:46 UTC, MauPalantir commented
@peterstadler can you take a look on this one? I have updated the PR and added steps for testing the feature.

2021-10-07 07:58 UTC, peterstadler commented
@MauPalantir many thanks for this! I had a quick look and yes, I see the "select file" and was able to point to another file. 
Yet, I found some minor issues that need to be addressed/discussed:
1. How do we point at manifestations, items , etc. within that other file? I guess we can do so by hand (by adding the ID as fragment identifier), but could that be supported by the select dialog as well?
2. The button "Got to linked resource" (next to the select file button)  does not work (for me). The same button does work under the "work" section, though.
3. The keyword search in the popup window "select file to link to" does not work. It always returns nothing, also under the "work" section. So maybe this is an issue on its own?

2024-01-18 17:33 UTC, closed without merging

2024-01-18 17:33 UTC, peterstadler commented
Closing this due to inactivity – but please feel free to reopen when there are any updates